### ISSUE TITLE
v2.2.0 Checklist

### ISSUE THREAD

**Issue by ejektaflex** [ejektaflex/Bountiful#33]
Things that need to be done before v2.2.0 can be released:
* [x] NBT support
* [x] Game Stages support
* [x] Give XP on bounty completion
* [x] Enforce minimum Forge version & compile against it
* [x] Allow min-max range for reward values
* [x] Adequate new vanilla bounties
* [x] New artwork for different bounty tiers
* [x] Final SP & MP testing

**Comment by drakray** [comment]
Can't wait for v2.2.0, as I just realize I need NBT for Thaumcraft Vis Crystal reward :/ XD
Keep up the good work :D

**Comment by Icebelly** [comment]
After seeing the bit about NBT tags I just realized how extremely helpful that's going to be. Hopefully it'll mean rewards like custom made tinkers' tools could be given, even ones with impossible stats. This will be wonderful!

**Comment by ejektaflex** [comment]
v2.2.0 finished as of 404c1d0. It has been uploaded and approved on CurseForge as well :^). 
Enjoy @drakray  & @Icebelly !
