### ISSUE TITLE
[1.13] Update checklist

### ISSUE THREAD

**Issue by ejektaflex** [ejektaflex/Bountiful#36]
Here's my checklist for what needs to be done before the update to 1.13 can be complete. Do note that just because everything may be checked off, that does not mean that it is done. Items may be added or removed at will.

* [ ] Implement writing to and reading from JSON files
* [ ] Reimplement Bounty Board TE
* [ ] Modify TE to accept Decrees
* [ ] TE should not store decrees on serialization, merely their tag ids for reconstruction later.
* [ ] Create Decree item
* [ ] Register NBT sensitive bounty item model
* [ ] Reimplement existing commands using Brigadier

**Comment by ejektaflex** [comment]
Moved to it's own repository for the time being, considering the MDK and it's changes make this viable for a full rewrite in the process.
